### ISSUE TITLE
Icon in store too big

### ISSUE THREAD

**Issue by Stoeoeoe** [GodotExplorer/FontAwesome#1]
Hi!

It seems that there is an issue with the icon you submitted for your plugin. The icon is rather big and is not being resized by the AssetLib as you can see in the attached screenshot:

![fa-issue](https://user-images.githubusercontent.com/4000949/29007084-37d35f30-7afc-11e7-9fa7-637681127268.png)

Probably it'd be good if you resubmitted the icon :)

Keep up the good work!

**Comment by i-need-to-tell-you-something** [comment]
In addition to looking unprofessional, this makes part of the editor unusable for people with smaller resolutions (incl. me).

**Comment by Geequlim** [comment]
It should be fix now

**Comment by i-need-to-tell-you-something** [comment]
Thanks. Confirming fixed on my instance of Godot which i havent closed since posting previous comment (so no restart or reinstall or such). Godot AssetLib updated its icon/logo cache automatically and it was fixed.
